<a href="https://colab.research.google.com/github/SyedaJannatul/Basic-Tutorials/blob/main/1_Tensorflow_Basic_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Initialization of tensor

In [ ]:
# Initialization tensor-constant
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

In [ ]:
x=tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
x=tf.ones((3,3)) #x=ones(shape=(3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
x=tf.zeros((3,3)) #x=tf.zeros(shape=(3,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
x=tf.eye(3) #eye= I-> for identity matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
#Standard normal distribution
x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[ 1.1923867  -1.319315    0.9843424 ]
 [ 0.4564766   0.5624695  -1.0556303 ]
 [ 0.09607963 -0.08906709  2.7081847 ]], shape=(3, 3), dtype=float32)


In [ ]:
#Standard uniform distribution
x=tf.random.uniform((1,3),minval=0,maxval=1)
print(x)

tf.Tensor([[0.9955102  0.44561696 0.35851836]], shape=(1, 3), dtype=float32)


In [ ]:
#similar range function in python
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [ ]:
x=tf.range(start=1,limit=10,delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [ ]:
#Type casting
y=tf.cast(x,dtype=tf.float64)
print(y)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


# Mathematical operation

In [ ]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])

In [ ]:
z=tf.add(x,y)
print(z)
m=x+y
print(m)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [ ]:
z=tf.subtract(x,y)
print(z)
m=x-y
print(m)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [ ]:
z=tf.divide(x,y)
print(z)
m=x/y
print(m)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [ ]:
z=tf.multiply(x,y)
print(z)
m=x*y
print(m)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [ ]:
z=tf.tensordot(x,y,axes=1)#after multiplication add all elements
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [ ]:
z=tf.tensordot(x,y,axes=0)
print(z)

tf.Tensor(
[[ 9  8  7]
 [18 16 14]
 [27 24 21]], shape=(3, 3), dtype=int32)


In [ ]:
z=tf.reduce_sum(x*y,axis=0)#after multiplication add all elements
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [ ]:
#Power function
z=tf.math.pow(x,5)
print(z)

z=x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [ ]:
x1=tf.constant([[1,2,3],[4,5,6]])
print(x1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
y1=tf.constant([[11,22,33],[44,55,66],[77,88,99]])
print(y1)

tf.Tensor(
[[11 22 33]
 [44 55 66]
 [77 88 99]], shape=(3, 3), dtype=int32)


In [ ]:
#Matrix multiplication
z=tf.matmul(x1,y1)
print(z)

z=x1@y1
print(z)

tf.Tensor(
[[ 330  396  462]
 [ 726  891 1056]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 330  396  462]
 [ 726  891 1056]], shape=(2, 3), dtype=int32)


# Indexing

In [ ]:
x=tf.constant([0,1,2,3,4,5,6,7,8,9])

In [ ]:
print(x[:])

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [ ]:
print(x[1:4])

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
print(x[:5])

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [ ]:
print(x[3:])

tf.Tensor([3 4 5 6 7 8 9], shape=(7,), dtype=int32)


In [ ]:
print(x[::2])

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [ ]:
print(x[::-1])

tf.Tensor([9 8 7 6 5 4 3 2 1 0], shape=(10,), dtype=int32)


In [ ]:
#find index
y=tf.constant([5,4,78,7])
indices=tf.constant([1,2])#here value work as index no.
x_ind=tf.gather(y,indices)
print(x_ind)

tf.Tensor([ 4 78], shape=(2,), dtype=int32)


In [ ]:
#matrix index
x=tf.constant([[1,2],
              [3,4],
              [5,6]])
print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
print(x[0,:])
print(x[0])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [ ]:
print(x[0:2,:])
print(x[0:2])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
print(x[0:3,:])
print(x[0:3])

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


# Reshaping

In [ ]:
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [ ]:
y=tf.reshape(x,(3,3))
print(y)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [ ]:
x=tf.range(6)
print(x)

tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)


In [ ]:
y=tf.reshape(x,(2,3))
print(y)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


syntax -> tf.transpose(a, perm=None, conjugate=False, name='transpose')

In [ ]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])#it works as tf.transpose(x, perm=[1, 0]) i.e row->column & column->row
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [ ]:
x = tf.constant([[1 + 1j, 2 + 2j, 3 + 3j],
                 [4 + 4j, 5 + 5j, 6 + 6j]])
tf.transpose(x, conjugate=True) #If x is complex, setting conjugate=True gives the conjugate transpose

<tf.Tensor: shape=(3, 2), dtype=complex128, numpy=
array([[1.-1.j, 4.-4.j],
       [2.-2.j, 5.-5.j],
       [3.-3.j, 6.-6.j]])>

In [ ]:
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]]) 
tf.transpose(x) #default to perm=[2,1,0]

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])>

 x =      1  2  3     7   8   9
          4  5  6     10  11  12

here 0->2, 1->2, 2->3. so in x' will be 0->3, 1->2, 2->2 
since here [2,1,0].
                    
 x'=      1  7     2  8     3  9
          4  10    5  11    6  12

In [ ]:
tf.transpose(x, perm=[0, 2, 1])

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])>

 x =      1  2  3     7   8   9
          4  5  6     10  11  12

here 0->2, 1->2, 2->3. so in x' will be 0->2, 1->3, 2->2 
since here [0,2,1].
          
 x'=      1  4     7  10   
          2  5     8  11   
          3  6     9  12